metric: VOC
map_type: integral
num_classes: 3

TrainDataset:
  name: VOCDataSet
  dataset_dir: dataset/dog_mouse_other_voc
  anno_path: train.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: dataset/dog_mouse_other_voc
  anno_path: valid.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: dataset/dog_mouse_other_voc/label_list.txt
